### ISSUE TITLE
[BUG] Unexpected error fetching MiWifi updater data

### ISSUE THREAD

**Issue by emimor123** [dmamontov/hass-miwifi#224]
**Describe the bug**
Thousands of this error per day in log.

2024-06-12 23:12:33.462 ERROR (MainThread) [custom_components.miwifi.updater] Unexpected error fetching MiWifi updater data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miwifi/updater.py", line 290, in update
    await self._async_prepare(method, self.data)
  File "/config/custom_components/miwifi/updater.py", line 431, in _async_prepare
    await action(data)
  File "/config/custom_components/miwifi/updater.py", line 898, in _async_prepare_device_list
    self.add_device(device, action=action, integrations=integrations)
  File "/config/custom_components/miwifi/updater.py", line 1019, in add_device
    _device: dict[str, Any] = self._build_device(device, integrations)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miwifi/updater.py", line 1082, in _build_device
    ip_attr: dict | None = device["ip"][0] if "ip" in device else None
                           ~~~~~~~~~~~~^^^

**Please complete the following information:**
 - HASS version: 2024.6.2 ( same in other previous versions )
 - Component version 3.0.0
 - Router model AX3600
 - Router firmware version 3.0.22

**Comment by Zhimiping** [comment]
Try replacing the 1082 lines of code with ：

ip_attr: dict | None = device["ip"][0] if "ip" in device and device["ip"] else None
