### ISSUE TITLE
Erreur new version 2.0.5 ax3600

### ISSUE THREAD

**Issue by Mick51** [dmamontov/hass-miwifi#28]
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/miwifi/updater.py:843
Integration: MiWiFi (documentation, issues)
First occurred: 22:34:36 (1 occurrences)
Last logged: 22:34:36

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/miwifi/__init__.py", line 86, in async_start
    await updater.update(True)
  File "/config/custom_components/miwifi/updater.py", line 236, in update
    await self._async_prepare(method, self.data)
  File "/config/custom_components/miwifi/updater.py", line 348, in _async_prepare
    await action(data)
  File "/config/custom_components/miwifi/updater.py", line 678, in _async_prepare_device_restore
    self._clean_devices()
  File "/config/custom_components/miwifi/updater.py", line 843, in _clean_devices
    delta = now - datetime.strptime(
TypeError: strptime() argument 1 must be str, not list

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.6

@Mick51 Thanks. Please check.

**Comment by Mick51** [comment]
Problem solved, thanks for the fast fix.  😉

**Comment by dmamontov** [comment]
My pleasure)
