### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by IvAn-source-git** [dmamontov/hass-miwifi#34]
Logger: homeassistant
Source: custom_components/miwifi/helper.py:102
Integration: MiWifi ([documentation](https://github.com/dmamontov/hass-miwifi), [issues](https://github.com/dmamontov/hass-miwifi/issues))
First occurred: 10:26:25 (216 occurrences)
Last logged: 12:28:15

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/miwifi/device_tracker.py", line 319, in _handle_coordinator_update
    is_connected = parse_last_activity(
  File "/config/custom_components/miwifi/helper.py", line 102, in parse_last_activity
    return datetime.strptime(last_activity, "%Y-%m-%dT%H:%M:%S")
TypeError: strptime() argument 1 must be str, not tuple

**Comment by dmamontov** [comment]
Update to the latest version and remove and add again. this bug has been fixed

I also recommend emptying the folder: config/.storage/miwifi

**Comment by IvAn-source-git** [comment]
Logger: homeassistant
Source: custom_components/miwifi/device_tracker.py:370
Integration: MiWifi (documentation, issues)
First occurred: 16:41:55 (14 occurrences)
Last logged: 16:49:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/miwifi/device_tracker.py", line 312, in _handle_coordinator_update
    self._update_entry(device.get(ATTR_TRACKER_ENTRY_ID, None))
  File "/config/custom_components/miwifi/device_tracker.py", line 370, in _update_entry
    if self._updater == self.hass.data[DOMAIN][entry_id][UPDATER]:
KeyError: '5310af966610a968dfaaa8721b5b75b7'

**Comment by IvAn-source-git** [comment]
I have 2 miwifi. 1 - AP mode. 2 - Mesh.

**Comment by dmamontov** [comment]
fix - https://github.com/dmamontov/hass-miwifi/releases/tag/v2.1.0
