### ISSUE TITLE
Error news home assistant 2022.4

### ISSUE THREAD

**Issue by Mick51** [dmamontov/hass-miwifi#36]
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Capteur (documentation, issues)
First occurred: 18:37:13 (2 occurrences)
Last logged: 18:37:13

Error adding entities for domain sensor with platform miwifi
Error while setting up miwifi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:529
Integration: Commutateur (documentation, issues)
First occurred: 18:37:12 (2 occurrences)
Last logged: 18:37:13

Error adding entities for domain switch with platform miwifi
Error while setting up miwifi platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

Logger: homeassistant.components.light
Source: helpers/entity_registry.py:529
Integration: Lumière (documentation, issues)
First occurred: 18:36:24 (2 occurrences)
Last logged: 18:36:24

Error adding entities for domain light with platform miwifi
Error while setting up miwifi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:529
Integration: Capteur binaire (documentation, issues)
First occurred: 18:36:24 (2 occurrences)
Last logged: 18:36:24

Error adding entities for domain binary_sensor with platform miwifi
Error while setting up miwifi platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by dmamontov** [comment]
fix - https://github.com/dmamontov/hass-miwifi/releases/tag/v2.1.0
