### ISSUE TITLE
Unable to connect my MI Wifi Router 4A Gigabit

### ISSUE THREAD

**Issue by brunob78** [dmamontov/hass-miwifi#39]
I'm trying to connect my router MI 4A Gigabit with your integration but it doesn't work.
![image](https://user-images.githubusercontent.com/76729879/162228421-2b382cb6-8aba-44af-9416-a678131e6474.png)

I have an error message "Invalid IP". I try also try with IP 192.168.31.1 and have the same issue.

**With the DEBUG mode in HA I have catch this informations:**

2022-04-07 16:48:20 DEBUG (MainThread) [custom_components.miwifi.luci] Connection error ConnectError('All connection attempts failed')
2022-04-07 16:48:20 DEBUG (MainThread) [custom_components.miwifi.updater] Finished fetching MiWifi updater data in 0.012 seconds (success: True)
2022-04-07 16:48:20 DEBUG (MainThread) [custom_components.miwifi.config_flow] Verify access code: 404
2022-04-07 16:48:32 DEBUG (MainThread) [custom_components.miwifi.luci] Connection error ConnectError('All connection attempts failed')
2022-04-07 16:48:32 DEBUG (MainThread) [custom_components.miwifi.updater] Finished fetching MiWifi updater data in 0.013 seconds (success: True)
2022-04-07 16:48:32 DEBUG (MainThread) [custom_components.miwifi.config_flow] Verify access code: 404
2022-04-07 16:48:56 DEBUG (MainThread) [custom_components.miwifi.luci] Connection error ConnectTimeout('')
2022-04-07 16:48:56 DEBUG (MainThread) [custom_components.miwifi.updater] Finished fetching MiWifi updater data in 7.517 seconds (success: True)
2022-04-07 16:48:56 DEBUG (MainThread) [custom_components.miwifi.config_flow] Verify access code: 404

Could you help me?

**Comment by dmamontov** [comment]
He was unable to get a fast response from your router. Check the IP and ping your router.

Authorization should take less than 5 seconds.

Try to spot it and send it to me.

**Comment by brunob78** [comment]
Ping of the router is OK from terminal on HA
![image](https://user-images.githubusercontent.com/76729879/162231054-d4110138-4340-481a-9ba9-6fe0de248e8f.png)

**Comment by dmamontov** [comment]
Try going to: http://192.168.31.1/cgi-bin/luci/api/misystem/topo_graph
What will give?

**Comment by dmamontov** [comment]
And the miwifi firmware version is possible?

**Comment by brunob78** [comment]
{"show":0,"graph":{"locale":"Home
","ssid":"Xiaomi_Bbo_Verneuil","name":"Xiaomi_Bbo_Verneuil","channel":"release","hardware":"R4A","mode":0,"color":101,"ip":"192.168.31.1"},"code":0}

System versionMAC address
Mi Router 4A Giga Version MiWiFi Release 3.0.27

Le jeu. 7 avr. 2022 à 17:13, Dmitry Mamontov ***@***.***> a
écrit :

**Comment by Sheyla1996** [comment]
Same error for Mi Router AX1800, when i try config the integration give me a error "Invalid IP"

**Comment by Sheyla1996** [comment]
I have updated to 2.2.1 and changed the last field to 60 but it still gives the error

**Comment by dmamontov** [comment]
Is it possible to log in debug mode?

**Comment by brunob78** [comment]
I have installed the version 2.28.69 but it's chineese version and now I have a lot of difficulties to configure miwifi even with translation.

**Comment by dmamontov** [comment]
If you find a European one, throw it off, I'll take it apart and see. but I don't think it will make much of a difference.

I need logs from the latest version of the component, they are a little more advanced there. only with debug enabled

you may also have some kind of firewall or something.

**Comment by Sheyla1996** [comment]
2022-04-08 11:55:14 DEBUG (MainThread) [custom_components.miwifi.luci] Connection error ConnectTimeout('')
2022-04-08 11:55:14 DEBUG (MainThread) [custom_components.miwifi.updater] Finished fetching MiWifi updater data in 20.009 seconds (success: True)
2022-04-08 11:55:14 DEBUG (MainThread) [custom_components.miwifi.config_flow] Verify access code: 404

**Comment by dmamontov** [comment]
@Sheyla1996 Install from the latest master. And repeat the game with timeouts.

And send the url to the web interface

**Comment by Sheyla1996** [comment]
I don't get the integration.

I have deleted from HACS the integration, I have restarted HA.
I have downloaded the main branch and copied the miwifi folder to the custom_components folder and restarted HA
When I go to the integrations I don't get

**Comment by dmamontov** [comment]
no. just select the beta version in hacs and select the main version there

**Comment by brunob78** [comment]
@dmamontov I have installed the version V2.2.0 and my router 4A is on version 2.28.69 and have always an error

2022-04-08 12:25:37 DEBUG (MainThread) [custom_components.miwifi.luci] Connection error ConnectError('[Errno -3] Try again')
2022-04-08 12:25:37 DEBUG (MainThread) [custom_components.miwifi.updater] Finished fetching MiWifi updater data in 5.015 seconds (success: True)
2022-04-08 12:25:37 DEBUG (MainThread) [custom_components.miwifi.config_flow] Verify access code: 404

**Comment by dmamontov** [comment]
The name server returned a temporary failure indication. Try again later." Your DNS is acting up.

**Comment by dmamontov** [comment]
It's definitely not the component. Look towards your DNS

@brunob78 everyone also received the url of the page for authorization and after it

**Comment by brunob78** [comment]
@dmamontov for your information, my HA network was 192.168.0.xxx, my Mi 4A router has IP local 192.168.0.106 and the managment console is accesible at 192.168.31.1
I tried to connect the integration with both IPs without success. I tried with the IP alone but also by adding http:// in front of the IP
I have

**Comment by dmamontov** [comment]
Do you have any vpn or proxy turned on yet?

**Comment by brunob78** [comment]
even if I tried with my local IP of HA I wasn't able to add the integration

**Comment by brunob78** [comment]
From HA I'm not able to ping 192.168.31.1 but I can ping 192.168.0.106 wich is my local IP for MI 4A Router

**Comment by dmamontov** [comment]
@brunob78

31.1 (ip by default) is correct. And it gives an auto_discovery message, not an integration. and this is not an error that occurs. error below.

Please send full urls

Ping and Access from Python work differently. The standard client is used.

You definitely have a DNS error

https://www.google.com/search?q=Connect+Errno+-3

The only thing I can suggest so far is to try installing the main version from beta and change it with timeouts

**Comment by brunob78** [comment]
Ok thanks I'm loooking for DNS error

**Comment by dmamontov** [comment]
Another option is to deploy a clean portable version of hass on your local PC and check the integration

**Comment by dmamontov** [comment]
@brunob78 everyone also received the url of the page for authorization and after it

Maybe it will show a little) The important thing is that the api works in the same way as the web interface.

**Comment by Sheyla1996** [comment]
Ok I have downloaded the main version from HACS but I can't find the URL you say

**Comment by dmamontov** [comment]
@Sheyla1996 URL in the browser when you go to the router.

**Comment by Sheyla1996** [comment]
http://192.168.31.1/cgi-bin/luci/web

**Comment by dmamontov** [comment]
@Sheyla1996

You can execute on the server side and send a screenshot

```bash
ping 192.168.31.1
telnet 192.168.31.1 80
```

**Comment by Sheyla1996** [comment]
My bug was fixed by going back to version 7.4 of Home Assistant OS. In version [8.0rc1 the wifi does not work](https://github.com/home-assistant/operating-system/issues/1837)

**Comment by dmamontov** [comment]
@brunob78 Did you manage to solve the problem?

**Comment by brunob78** [comment]
No I'm on holiday for 2 weeks.

Le sam. 9 avr. 2022, 14:51, Dmitry Mamontov ***@***.***> a
écrit :

**Comment by effelle** [comment]
I have a similar issue with my AX5 (RA67) in mesh mode, HACS version V2.5.
The main router (on 31.1) is recognized but can't be added, the leaf (on 31.43) is registered in Home Assistant without issues.
```
{"show":1,"graph":{"ssid":"EffE-Domus","color":100,"ip":"192.168.31.1","locale":"Home","name":"XIAOMI-R1","channel":"release","hardware":"RA67",
"mode":4,"leafs":[{"ssid":"EffE-Domus","color":100,"ip":"192.168.31.43","locale":"Guest","name":"Xiaomi-R2","channel":"release","hardware":"RA67","mode":8,"version":""}]},"code":0}
```
I can ping and access the main router using telnet but the HA integration always returns an invalid IP:
```2022-04-22 10:35:56 ERROR (MainThread) [custom_components.miwifi.updater] Unexpected error fetching MiWifi updater data: '192.168.31.1'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
return await self.update_method()
File "/config/custom_components/miwifi/updater.py", line 249, in update
await self._async_prepare(method, self.data)
File "/config/custom_components/miwifi/updater.py", line 376, in _async_prepare
await action(data)
File "/config/custom_components/miwifi/updater.py", line 744, in _async_prepare_device_list
device[ATTR_TRACKER_UPDATER_ENTRY_ID] = integrations[self.ip][
KeyError: '192.168.31.1'
```
Probably related (?), the leaf router doesn't reports any device connected and some sensors can't be turned on.
![xiaomi](https://user-images.githubusercontent.com/7702766/164728051-5839f5c8-1b20-4512-8990-a5e787a1b9fa.png)

**Comment by dmamontov** [comment]
@effelle you have an error, can I have diagnostic data? so that I can fix

**Comment by effelle** [comment]
I assume you refer to logger info?
[logs.txt](https://github.com/dmamontov/hass-miwifi/files/8541744/logs.txt)

**Comment by dmamontov** [comment]
> I assume you refer to logger info? [logs.txt](https://github.com/dmamontov/hass-miwifi/files/8541744/logs.txt)

Thank you. As I thought. I'll release a fix now.

**Comment by dmamontov** [comment]
@effelle https://github.com/dmamontov/hass-miwifi/releases/tag/v2.5.1

**Comment by effelle** [comment]
Sure thing, I'll test it as soon as I'll see it. Will you release it on Beta channel?

**Comment by dmamontov** [comment]
> Sure thing, I'll test it as soon as I'll see it. Will you release it on Beta channel?

Already released) There is no point in beta)

**Comment by effelle** [comment]
Fixed, thanks Dmitry.
I assume I need to wait some time to see some correct stats?
![xiaomi](https://user-images.githubusercontent.com/7702766/164736104-6c06f101-6724-4327-8fc2-afbfe03286e8.png)
I have way more device connected and the sensors are still grayed out.

**Comment by dmamontov** [comment]
@effelle In your screenshot you can see 2 links to download diagnostic data, click on them and send them to me. I'll try to figure it out. Of course, I have ideas about what's going on. But confirmation is needed.

**Comment by effelle** [comment]
Sure!
First link:
[config_entry-miwifi-b45e9cf2f0559ed023ba806eed022113.json.txt](https://github.com/dmamontov/hass-miwifi/files/8542056/config_entry-miwifi-b45e9cf2f0559ed023ba806eed022113.json.txt)

Second link:
[config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json.txt](https://github.com/dmamontov/hass-miwifi/files/8542057/config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json.txt)

**Comment by dmamontov** [comment]
> Sure! First link: [config_entry-miwifi-b45e9cf2f0559ed023ba806eed022113.json.txt](https://github.com/dmamontov/hass-miwifi/files/8542056/config_entry-miwifi-b45e9cf2f0559ed023ba806eed022113.json.txt)
> 
> Second link: [config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json.txt](https://github.com/dmamontov/hass-miwifi/files/8542057/config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json.txt)

I need time to study the data. Thank you. I will write as clear as possible.

**Comment by effelle** [comment]
No need to hurry. Good integration takes time and you already started very well.
To complete the picture, here is the list of all the sensors I can't enable for now:
```
Devices 2.4G
Devices 5G
Devices guest
Devices lan
Wifi 2.4G channel
Wifi 2.4G signal strength
Wifi 5G channel
Wifi 5G signal strength
Wifi 5G
Wifi guest
Dual band
Memory total
Memory usage
Uptime
```

**Comment by viktak** [comment]
I have the same router (Xiaomi Mi Router 4A Gigabit Edition) with the same problem ("Invalid IP" when trying to configure this integration). Running OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.295.67054-13df80d

Let me know if I can help testing.

**Comment by dmamontov** [comment]
@viktak With pure openwrt, this integration does not work. Only MiWifi (original firmware)

**Comment by viktak** [comment]
Ah, I see. I misunderstood this part: "Many more Xiaomi and Redmi routers supported by MiWiFi (OpenWRT - Luci API)"
Sorry about that.

**Comment by dmamontov** [comment]
@viktak It's okay. I'll probably add a check to the flow)

**Comment by dmamontov** [comment]
@effelle https://github.com/dmamontov/hass-miwifi/releases/tag/v2.6.0

Try to update.

**Comment by effelle** [comment]
Hi Dmitry, 
I've updated the integration but the sensors are still grayed out and marked as not available.
[config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json (1).txt](https://github.com/dmamontov/hass-miwifi/files/8590766/config_entry-miwifi-87f5632f06ed5086300a34e5964038b6.json.1.txt)

**Comment by dmamontov** [comment]
@effelle I just noticed from your screenshot that in my opinion they are not activated for you. Turn them on. They are disabled by default.

**Comment by effelle** [comment]
Hi,
I did enable them but even after some time they were still grayed out.
Updating HACS to the latest release solved the issue (with others
integrations too).
I did not enabled all the sensors yet, I'll do it later today just to check
if all are working, but I think is safe to say problem solved.

F.

**Comment by dmamontov** [comment]
For now, I'll close the issue. There is no activity, and problems with integration. If anyone has problems it is better to create new ones.
