### ISSUE TITLE
Update for device_tracker.kmd1027703 fails

### ISSUE THREAD

**Issue by shadson** [dmamontov/hass-miwifi#5]
Hello,

My router is scheduled to reboot every night, so the connection to it is down during few minutes.
Here is the log record:

Logger: homeassistant.helpers.entity
Source: custom_components/miwifi/device_tracker.py:260
Integration: MiWiFi (documentation)
First occurred: 3:58:04 AM (42 occurrences)
Last logged: 4:04:54 AM

Update for device_tracker.kmd1027703 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/miwifi/device_tracker.py", line 260, in async_update
    self._device["ip"] = device["ip"][0]["ip"] if "ip" in device else "0:0:0:0"
IndexError: list index out of range

Perhaps, list "_device[]" is empty in such cases, so it makes reason to frame it with "try / except". 

Thanks

**Comment by dmamontov** [comment]
Yes thank you. I'll do it. There was no such case before.

**Comment by dmamontov** [comment]
Fixed in version 1.2.5. Please check

**Comment by shadson** [comment]
Thank you, seems to be fixed.

Got exception in another place:
File "/config/custom_components/miwifi/core/luci.py", line 322
Will check later and open new issue if confirmed.
