### ISSUE TITLE
ax9000 problem with "5G Game" wifi

### ISSUE THREAD

**Issue by 2pirko** [dmamontov/hass-miwifi#7]
2021-10-28 22:22:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/miwifi/core/luci_data.py", line 168, in refresh
await self.async_update()
File "/config/custom_components/miwifi/core/luci_data.py", line 93, in async_update
await self.api.prepare_data()
File "/config/custom_components/miwifi/core/luci.py", line 133, in prepare_data
await self.set_devices_list()
File "/config/custom_components/miwifi/core/luci.py", line 225, in set_devices_list
device["connection"] = CONNECTION_RANGES[device["type"]]
KeyError: 6

**Comment by dmamontov** [comment]
Fixed the bug itself, but haven't added support for new types yet. For this I would like to ask for help. Can you send the output of the following command http://<your ip>/cgi-bin/luci;stok=<your stock>/api/misystem/devicelist

mac addresses and ip can be removed if desired.

**Comment by 2pirko** [comment]
Annswer sent to your email address

**Comment by dmamontov** [comment]
> Annswer sent to your email address

if it's not difficult, you can also output: http://(your ip)/cgi-bin/luci;stok=(your stock)/api/misystem/newstatus

**Comment by 2pirko** [comment]
Annwer sent to your email address

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v1.2.7

Added support for 6G Game mode
